source("plot1.R")
source("plot2.R")
source("plot3.R")
source("plot4.R")
#data <- getData()
#data <- getData("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip")
#data <- NULL
#plot1(data)
#plot2(data)
#plot3(data)
#plot4(data)
plot1()
plot2()
plot3()
plot4()